"""
List of dishes
"""

dishes = [
    "Barbecue Ribs",
    "Bruschette with Tomato",
    "Caesar Salad",
    "Califlower penne",
    "California maki",
    "Caprese Salad",
    "Cheeseburger",
    "Chicken Fajitas",
    "Chicken milanese",
    "Chicken wings",
    "Chilli con carne",
    "Ebiten maki",
    "Fettuccine Alfredo",
    "Fish and chips",
    "French fries with sausages",
    "Katsu Curry",
    "Lasagne",
    "Linguine with clams",
    "Meatballs with sauce",
    "Mushroom Risotto",
    "Pappardelle alla Bolognese",
    "Pasta Carbonara",
    "Pasta and Beans",
    "Pasta with Tomato and Basil",
    "Philadelphia maki",
    "Pizza",
    "Pork belly buns",
    "Pork sausage roll",
    "Ricotta stuffed Ravioli",
    "Risotto with seafood",
    "Salmon nigiri",
    "Scotch eggs",
    "Souvlaki",
    "Teriyaki Chicken donburi",
    "Tiramisù",
    "Tuna sashimi",
    "Vegetable Soup",
]
