spices = [
    "Achiote Seed",
    "Ajwain Seed",
    "Ajwan Seed",
    "Allspice Ground",
    "Allspice Whole",
    "Amchoor",
    "Anise",
    "Anise Star",
    "Aniseed Whole",
    "Annatto Seed",
    "Arrowroot",
    "Asafoetida",
    "Baharat",
    "Balti Masala",
    "Balti Stir Fry Mix",
    "Basil",
    "Bay Leaves",
    "Bay Leaves Chopped",
    "BBQ Seasoning",
    "Biryani Spice Mix",
    "Cajun Seasoning",
    "Caraway Seed",
    "Cardamom Ground",
    "Cardamom Whole",
    "Cassia",
    "Cassia Bark",
    "Cayenne Pepper",
    "Celery Leaf",
    "Celery Salt",
    "Celery Seed",
    "Chamomile",
    "Chervil",
    "Chicken Seasoning",
    "Chilli Crushed",
    "Chilli Ground",
    "Chilli Pepper",
    "Chillies Whole",
    "China Star",
    "Chinese 5 Spice",
    "Chives",
    "Cinnamon Bark",
    "Cinnamon Ground",
    "Cinnamon Powder",
    "Cinnamon Sticks",
    "Cloves Ground",
    "Cloves Whole",
    "Colombo Powder",
    "Coriander Ground",
    "Coriander Leaf",
    "Coriander Seed",
    "Creole Seasoning",
    "Cumin Ground",
    "Cumin Seed",
    "Cumin Seed Black",
    "Cumin Seed Royal",
    "Curly Leaf Parsley",
    "Curry Chinese",
    "Curry Hot",
    "Curry Leaves",
    "Curry Madras Medium",
    "Curry Mild",
    "Curry Thai Green",
    "Curry Thai Red",
    "Dhansak Spice Mix",
    "Dill Herb",
    "Dill Leaf",
    "Dill Seed",
    "Fajita Seasoning",
    "Fennel Seed",
    "Fenugreek Ground",
    "Fenugreek Leaf",
    "Fenugreek Seed",
    "Fines Herbes",
    "Fish Seasoning",
    "Five Spice Mix",
    "French Lavender",
    "Galangal Ground",
    "Garam Masala",
    "Garlic Chips",
    "Garlic Granules",
    "Garlic Powder",
    "Garlic Salt",
    "German Chamomile",
    "Ginger Root",
    "Ginger Ground",
    "Green Cardamom",
    "Herbes de Provence",
    "Jalfrezi Curry Powder",
    "Jalfrezi Mix",
    "Jerk Seasoning",
    "Juniper Berries",
    "Kaffir Leaves",
    "Korma Curry Powder",
    "Korma Mix",
    "Lamb Seasoning",
    "Lavender",
    "Lemon Grass",
    "Lemon Grass Chopped",
    "Lemon Pepper",
    "Lime Leaves",
    "Lime Leaves Ground",
    "Liquorice Root",
    "Mace Ground",
    "Mace Whole",
    "Mango Powder",
    "Marjoram",
    "Methi",
    "Methi Leaves",
    "Mexican Salsa Mix",
    "Mint",
    "Mixed Herbs",
    "Mixed Spice",
    "Mulled Cider Spices",
    "Mulled Wine Spices",
    "Mustard Powder",
    "Mustard Seed Black",
    "Mustard Seed Brown",
    "Mustard Seed White",
    "Mustard Seed Yellow",
    "Nigella",
    "Nutmeg Ground",
    "Nutmeg Whole",
    "Onion Seed",
    "Orange Zest",
    "Oregano",
    "Paella Seasoning",
    "Paprika",
    "Paprika Hungarian",
    "Paprika Smoked",
    "Parsley",
    "Parsley Flat Leaf",
    "Pepper Black Coarse",
    "Pepper Black Ground",
    "Pepper White Ground",
    "Peppercorns Black",
    "Peppercorns Cracked Black",
    "Peppercorns Green",
    "Peppercorns Mixed",
    "Peppercorns Pink",
    "Peppercorns Szechwan",
    "Peppercorns White",
    "Pickling Spice",
    "Pimento Berries",
    "Pimento Ground",
    "Piri Piri Seasoning",
    "Pizza Topping Mix",
    "Poppy Seed",
    "Pot Marjoram",
    "Poudre de Colombo",
    "Ras-el-Hanout",
    "Rice Paper",
    "Rogan Josh Curry Powder",
    "Rogan Josh Mix",
    "Rose Baie",
    "Rosemary",
    "Saffron",
    "Sage",
    "Sea Salt Coarse",
    "Seasoning Salt",
    "Self Adhesive Spice Labels",
    "Sesame Seed",
    "Spearmint",
    "Spice Charts",
    "Steak Seasoning",
    "Sumac Ground",
    "Sweet Basil",
    "Sweet Laurel",
    "Tagine Seasoning",
    "Tandoori Masala",
    "Tandoori Mix",
    "Tarragon",
    "Thai Creen Curry Mix",
    "Thai Red Curry Mix",
    "Thai Stir Fry",
    "Thyme",
    "Tikka Masala",
    "Tikka Masala Curry Powder",
    "Turmeric",
    "Turmeric Powder",
    "Vanilla Bean",
    "Vanilla Pods",
    "Vegetable Seasoning",
    "Zahtar Spice Mix",
]
