sushi = [
    "Abalone",
    "Alaskan pink shrimp",
    "Amberjack",
    "Bastard halibut",
    "Bloody clam",
    "Botan shrimp",
    "Crab",
    "Dotted gizzard shad",
    "Eel",
    "Firefly squid",
    "Greater amberjack",
    "Halfbeak",
    "Horned turban",
    "Japanese horse mackerel",
    "Japanese sea bass",
    "Japanese spanish mackerel",
    "Japanese style-chunky omelette",
    "Japanese whiting",
    "Mackerel",
    "Milt",
    "Mirugai clam",
    "Octopus",
    "Orient clam",
    "Oyster",
    "Rosy seabass",
    "Salmon roe",
    "Salmon",
    "Scallop",
    "Sea bream",
    "Skipjack tuna",
    "Small amberjack",
    "Squid",
    "Trough shells",
    "Trout",
    "Tuna",
    "White trevally",
    "Whitespotted conger",
]
